theme = "default"

[editor] 
true-color = true
idle-timeout = 100
completion-trigger-len = 2
auto-save = true 
bufferline = "always"

line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

"A-h" = "move_char_left" 
"A-j" = "move_line_down" 
"A-k" = "move_line_up" 
"A-l" = "move_char_right" 
"A-a" = "normal_mode"
"A-w" = ":wa"

[keys.normal]
"A-w" = ":wa"
